apiVersion: v1
kind: Deployment
metadata:
  name: roboshop-shiipingweb
spec:
  template:
    metadata:
      labels: 
        app: web
spec:
  containers:
    - name: clahan-image
      image: clahandevops/clahan-image:latest
      ports:
        - conatinerport: 80
  replicas: 3
  selector: 
    matchlabels: 
      app: web
      