apiVersion: v1
kind: Deployment
metadata:
  name: roboshop-shiipingweb
spec:
  template:
    metadata: 
      labels: 
        app: web
    spec:
      containers:
        - image: clahandevops/clahan-image:latest
          name: clahanimage
          ports:
            - conatinerPort: 80
  replicas: 3
  selector: 
    matchlabels: 
      app: web

